linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - fmt.Println
      - fmt.Printf
      - fmt.Print
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
  golint:
    min-confidence: 0.8
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - misspell

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

